all:
  hosts:
    local:
      ansible_host: localhost
      ansible_connection: local
      vars:
        git_client_name: Jason Herman
        git_client_email: jason@redconfetti.com
        timezone: America/Los_Angeles
